### ISSUE TITLE
Unhandled promise rejection error

### ISSUE THREAD

**Issue by Robert16296** [Ecostack/TicketSwapper#1]
Using 
```
ticketswapper https://www.ticketswap.nl/event/blackout-xl-noisia-black-sun-empire-and-more/floor-tickets/2e758124-e642-4a1a-a1ab-45512785ea50/1536059 TOKEN_REDACTED
```

After ~10 minutes, not always.

```
(node:2460) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token B in JSON at position 0 
at JSON.parse (<anonymous>)
at Object.<anonymous> (C:\laragon\bin\nodejs\node-v12\node_modules\ticketswapper\dist\event.js:104:23) 
at Generator.next (<anonymous>)
at fulfilled (C:\laragon\bin\nodejs\node-v12\node_modules\ticketswapper\dist\event.js:5:58) 
at processTicksAndRejections (internal/process/task_queues.js:82:5)
(node:2460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) 
(node:2460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**Comment by Ecostack** [comment]
Hi Robert,

I will have a look at it later!

**Comment by Ecostack** [comment]
This specific issues is fixed in the latest build.
