### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Defmatt792** [Ecostack/TicketSwapper#6]
Hi,

I am not sure but it seems that TicketSwapper is not working anymore.
When I try to run the usual code (which worked perfectly fine until now), I receive the following message:

---------------------
(node:30843) UnhandledPromiseRejectionWarning: Error: Event id could not be used.
    at Object.<anonymous> (/usr/local/lib/node_modules/ticketswapper/dist/event.js:65:15)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/ticketswapper/dist/event.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
---------------------

Any clue about what to do??

**Comment by atais** [comment]
same

**Comment by Ecostack** [comment]
Hey everyone, I have not been very active with the project in the past due to COVID. The error is most likely due to a change in the API from TicketSwap.

**Comment by doxt3r** [comment]
up !
thanks !

**Comment by iblamejonas** [comment]
Since festivals are slowly getting started again. Any chance you could try to fix it when you got the time. You would be a life saver :)

**Comment by doxt3r** [comment]
Any update please ? Thanks

**Comment by Ecostack** [comment]
As I said before, I am not using this project anymore. For the moment, I am too busy to be involved in it. Please have a look at their API and change the project as you like.

**Comment by jeblancosopra** [comment]
Hello Ecostack, where can I find the API Reference?
